In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Our Dataset

In [18]:
df = pd.read_csv(r'C:\Users\vaish\OneDrive\Documents\Dataset51.csv')
df
# Company :
# 0-->Phonak
# 1-->Auditech
# 2-->Unitron

    Price  Hearing Loss in decibels                 Type  Company
0   68000                     75.00       Behind The Ear        0
1   12500                     35.00       Behind The Ear        0
2   43000                     50.00       Behind The Ear        0
3    7500                     30.00           In The Ear        1
4   12500                     50.50           In The Ear        0
5    7500                     60.00  Completely in Canal        1
6   12500                     75.00  Completely in Canal        0
7    7500                     45.00           In The Ear        1
8    6000                     80.45  Completely in Canal        0
9    8000                     48.00           In The Ear        1
10  20000                     68.00  Completely in Canal        0
11  25000                     75.00  Completely in Canal        2
12  56500                     64.00       Behind The Ear        2
13  18000                     48.00       Behind The Ear        2
14  46500                     90.00  Completely in Canal        2
15  40000                     52.00           In The Ear        2
16  40000                     88.00  Completely in Canal        2
17  10000                     65.00  Completely in Canal        2

# Convert to float

In [19]:
df['Price'] = pd.to_numeric(df['Price'], downcast='float')

In [22]:
df['Hearing Loss in decibels'] = pd.to_numeric(df['Hearing Loss in decibels'], downcast='float')

In [37]:
df

      Price  Hearing Loss in decibels                 Type  Company
0   68000.0                 75.000000       Behind The Ear        0
1   12500.0                 35.000000       Behind The Ear        0
2   43000.0                 50.000000       Behind The Ear        0
3    7500.0                 30.000000           In The Ear        1
4   12500.0                 50.500000           In The Ear        0
5    7500.0                 60.000000  Completely in Canal        1
6   12500.0                 75.000000  Completely in Canal        0
7    7500.0                 45.000000           In The Ear        1
8    6000.0                 80.449997  Completely in Canal        0
9    8000.0                 48.000000           In The Ear        1
10  20000.0                 68.000000  Completely in Canal        0
11  25000.0                 75.000000  Completely in Canal        2
12  56500.0                 64.000000       Behind The Ear        2
13  18000.0                 48.000000       Behind The Ear        2
14  46500.0                 90.000000  Completely in Canal        2
15  40000.0                 52.000000           In The Ear        2
16  40000.0                 88.000000  Completely in Canal        2
17  10000.0                 65.000000  Completely in Canal        2

In [38]:
print(df.shape)

(18, 4)

In [39]:
df.drop(['Type'], axis = 1)

      Price  Hearing Loss in decibels  Company
0   68000.0                 75.000000        0
1   12500.0                 35.000000        0
2   43000.0                 50.000000        0
3    7500.0                 30.000000        1
4   12500.0                 50.500000        0
5    7500.0                 60.000000        1
6   12500.0                 75.000000        0
7    7500.0                 45.000000        1
8    6000.0                 80.449997        0
9    8000.0                 48.000000        1
10  20000.0                 68.000000        0
11  25000.0                 75.000000        2
12  56500.0                 64.000000        2
13  18000.0                 48.000000        2
14  46500.0                 90.000000        2
15  40000.0                 52.000000        2
16  40000.0                 88.000000        2
17  10000.0                 65.000000        2

# Define the input and output

In [26]:
X = df.iloc[:, 0:2].values
y = df.iloc[:, -1].values

# Build The Model

In [35]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential()
model.add(layers.Dense(3, kernel_initializer='uniform', input_shape=(2,)))
model.add(layers.Activation('softmax'))

loss_fn = keras.losses.SparseCategoricalCrossentropy()
model.compile(loss=loss_fn, optimizer='adam')
hist = model.fit(X, y, epochs=20)

Epoch 1/20
1/1 [==============================] - 0s 169ms/step - loss: 107.9298
Epoch 2/20
1/1 [==============================] - 0s 4ms/step - loss: 85.0823
Epoch 3/20
1/1 [==============================] - 0s 5ms/step - loss: 62.2348
Epoch 4/20
1/1 [==============================] - 0s 5ms/step - loss: 39.3922
Epoch 5/20
1/1 [==============================] - 0s 5ms/step - loss: 41.6670
Epoch 6/20
1/1 [==============================] - 0s 3ms/step - loss: 51.0464
Epoch 7/20
1/1 [==============================] - 0s 3ms/step - loss: 50.6219
Epoch 8/20
1/1 [==============================] - 0s 6ms/step - loss: 43.7631
Epoch 9/20
1/1 [==============================] - 0s 4ms/step - loss: 32.3651
Epoch 10/20
1/1 [==============================] - 0s 5ms/step - loss: 19.6404
Epoch 11/20
1/1 [==============================] - 0s 5ms/step - loss: 24.1284
Epoch 12/20
1/1 [==============================] - 0s 3ms/step - loss: 25.7800
Epoch 13/20
1/1 [==============================] - 0s 3ms/step - loss: 24.3716
Epoch 14/20
1/1 [==============================] - 0s 4ms/step - loss: 20.3790
Epoch 15/20
1/1 [==============================] - 0s 5ms/step - loss: 14.2679
Epoch 16/20
1/1 [==============================] - 0s 6ms/step - loss: 8.9031
Epoch 17/20
1/1 [==============================] - 0s 4ms/step - loss: 10.6704
Epoch 18/20
1/1 [==============================] - 0s 4ms/step - loss: 8.0634
Epoch 19/20
1/1 [==============================] - 0s 5ms/step - loss: 3.0352
Epoch 20/20
1/1 [==============================] - 0s 5ms/step - loss: 2.8557

# Predicting The Output

In [43]:
model.predict(np.array([[8000.00, 40.00]]))
np.argmax(model.predict(np.array([[8000.00, 40.00]])), axis=1)

array([1], dtype=int64)